FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Chat.BFF.csproj", "./"]
RUN dotnet restore "Chat.BFF.csproj"
COPY . .
RUN dotnet build "Chat.BFF.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Chat.BFF.csproj" -c Release -o /app/publish

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:8080

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Chat.BFF.dll"]